### ISSUE TITLE
Iseult does not start when attempting to use with v2 data

### ISSUE THREAD

**Issue by adamtrobbins** [PrincetonUniversity/Iseult#14]
I attempted to run the new Iseult with v2 data in [ar3676@stellar-vis2 ~/scr/6_test/output]. An empty Iseult window briefly appeared and then I got the errors detailed in the attached image. My Python version is 3.11.7. 
<img width="789" alt="bug" src="https://github.com/user-attachments/assets/cfadd5ab-dbe7-420c-a50d-769ef19e55d4">

**Comment by bcaddy** [comment]
What's the full path to the data?

**Comment by adamtrobbins** [comment]
[/home/ar3676/scr/6_test/output]

**Comment by bcaddy** [comment]
I've figured out a fix for this but ran into some other bugs while I was at it. I'll update when I've got it working on this dataset.

**Comment by bcaddy** [comment]
I think I fixed it. Could you pull the new code and try it out?

**Comment by adamtrobbins** [comment]
As far as I can tell, it is now all working properly. Thank you.

**Comment by bcaddy** [comment]
Awesome, thanks
