### ISSUE TITLE
Error message when changing Skip size in Settings

### ISSUE THREAD

**Issue by ntoles** [PrincetonUniversity/Iseult#16]
<img width="1339" alt="image" src="https://github.com/user-attachments/assets/97c46391-75f7-4fdf-8eb5-f68e9c1a5317">

**Comment by bcaddy** [comment]
How do I reproduce this?

**Comment by ntoles** [comment]
Open Settings (or push capital S), type in Skip size (first field) to set
it to 1. Press enter.

**Comment by bcaddy** [comment]
This has been fixed in the latest commit to PR #9
