### ISSUE TITLE
Reload not working

### ISSUE THREAD

**Issue by ntoles** [PrincetonUniversity/Iseult#23]
Pressing Reload button triggers this error and program is unusable. It should check for the largest file in the directory. 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/licensed/anaconda3/2023.9/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/anatoly/tig/Bob-iseult/src/main_app.py", line 434, in OnReload
    self.parent.ReloadPath()
  File "/home/anatoly/tig/Bob-iseult/src/main_app.py", line 2180, in ReloadPath
    self.TimeStep.setMax(len(self.PathDict['Flds']))
  File "/home/anatoly/tig/Bob-iseult/src/main_app.py", line 342, in setMax
    feedbackKnob.setKnob(self.value)
  File "/home/anatoly/tig/Bob-iseult/src/main_app.py", line 3540, in setKnob
    self.RenewCanvas()
  File "/home/anatoly/tig/Bob-iseult/src/main_app.py", line 3003, in RenewCanvas
    self.RefreshCanvas(keep_view = keep_view)
  File "/home/anatoly/tig/Bob-iseult/src/main_app.py", line 3233, in RefreshCanvas
    self.LoadAllKeys()
  File "/home/anatoly/tig/Bob-iseult/src/main_app.py", line 2476, in LoadAllKeys
    filepath = os.path.join(self.dirname,self.PathDict['Param'][self.TimeStep.value-1])
                                         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range


<img width="1223" alt="image" src="https://github.com/user-attachments/assets/b101a25c-ffca-484b-97c6-981c89c26ef6">

**Comment by bcaddy** [comment]
Thanks, is this on `master` or one of the open PRs?

**Comment by ntoles** [comment]
***@***.*** ~/tig/Bob-iseult]$ git pull
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 10 (delta 8), reused 10 (delta 8), pack-reused 0
Unpacking objects: 100% (10/10), 3.47 KiB | 48.00 KiB/s, done.
From github.com:bcaddy/Iseult
   0bf88b8..ae34820  master-tv2Spectra         -> origin/master-tv2Spectra
 * [new branch]      master-bugfixFindingFiles ->
origin/master-bugfixFindingFiles
Updating 0bf88b8..ae34820
Fast-forward
 iseult.py           |  14 ++++++++++-
 src/data_loading.py | 110
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------
 src/main_app.py     |   2 +-
 3 files changed, 100 insertions(+), 26 deletions(-)

***@***.*** ~/tig/Bob-iseult]$ git branch
  mas-loadv2
  master
* master-tv2Spectra

**Comment by bcaddy** [comment]
Thanks, I'm not sure what the issue is yet but I can reproduce it so I'll work on figuring it out.

**Comment by bcaddy** [comment]
I found the issue. It will be a little time consuming to fix but shouldn't be too hard. Will update when I have a fix
