### ISSUE TITLE
matplotlib version check

### ISSUE THREAD

**Issue by ntoles** [PrincetonUniversity/Iseult#28]
Could you add a check of the matplotlib and/or anaconda version at the startup and exit if the version is too new with an error message that points to what module to load? This will eliminate easy mistakes and complaints. Unfortunately, nobody can read README.

**Comment by bcaddy** [comment]
Sure. 

Is the issue with the README that people don't remember to read it or that it is not readable?

**Comment by ntoles** [comment]
But a more relevant case is the users who already had it installed and just
update and suddenly things break. Or, they just forget to check the version
of matplotlib.
