### ISSUE TITLE
Electric charge density with non-unity mass ratio v2 data issue

### ISSUE THREAD

**Issue by adamtrobbins** [PrincetonUniversity/Iseult#45]
Checking the rho (electric charge density) option in the density for fields yields a plot of dens2 - dens1, but instead it should be dens2 / m2 - dens1 since the densities are mass densities (m * n), not the number densities (n). Hence the higher mass needs to be corrected for. 

This can be seen by loading /scratch/gpfs/ar3676/runs/1e_test/output in Iseult, a run with m2 = 25. Checking rho under density plot results in a plot which suggests that there are very large charge buildups all throughout the simulation which is not the case. rho should be very nearly 0 everywhere.

**Comment by ntoles** [comment]
I am confirming with Hayk if density is really a mass density.

**Comment by ntoles** [comment]
Indeed, it appears we need to divide by m!

**Comment by bcaddy** [comment]
Is it always the case that in Tristan v1 `densi` is a number density and in Tristan v2 the equivalent `dens2` is a mass density? What about `dens`/`dens1`?

**Comment by ntoles** [comment]
Apparently this is so.
All densities in v1 are number density, all densities in v2 are mass
densities (divided by electron mass). I did not appreciate this about v2
before.

**Comment by bcaddy** [comment]
Are they specifically divided by electron mass or the mass of that species? Based on what @adamtrobbins says I assume the latter.

**Comment by bcaddy** [comment]
Ok, I'll post a proposed fix shortly.

**Comment by bcaddy** [comment]
I've posted a proposed fix in PR #46. Let me know if it works.

**Comment by adamtrobbins** [comment]
The fix works - thanks!
